project:
  type: manuscript

manuscript:
  article: index.qmd

execute:
  freeze: true
  working-directory: ../

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default



