project:
  type: manuscript
  output-dir: .

manuscript:
  article: index.qmd

execute:
  freeze: true
  working-directory: ../

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default